# Site settings
title: Rah-E-Hidayat
description: ""
url: "http://www.rahehidayat.ca"

# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
collections:
  books:
    output: true
  hadees:
    output: true
  posts:
    output: true

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-sitemap
  - octopress-autoprefixer
  - octopress-paginate
