---
new_page_extension: html
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _books
  label: Books
  create: all
  match: "**/*"
- type: directory
  path: _hadees
  label: Hadees
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
